version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular-skeleton:latest
    container_name: angular-skeleton
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true